### ISSUE TITLE
TODO for now

### ISSUE THREAD

**Issue by m-luk** [remoteVoyager/Snek#1]
- [x] Create 'food' and snake getting bigger mechanisms 
- [x] Create and clean up UI
- [x] Do all the menus
