### ISSUE TITLE
TODO for now #2

### ISSUE THREAD

**Issue by m-luk** [remoteVoyager/Snek#3]
- [x] Add option to go back to main menu to the crash screen
- [x] Add scoring and score display
- [x] Rethink runloop and sub-loops execution
- [ ] Rethink ui.py text placing (mainly allow to centralize text)
- [ ] credits and leaderboard
- [ ] some barriers?

**Comment by m-luk** [comment]
as of 8c0dcf7f7d7a0c4f20bb887cb27c3d68775b45d6 score display works

**Comment by m-luk** [comment]
as of 89139213927b0880b02b082c71a9c4d0119b854e runloop changed for code readability, however menu performance dropped, new issue for that
